# Generated by Django 5.0.7 on 2025-03-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codereview',
            old_name='code_text',
            new_name='code_content',
        ),
        migrations.AddField(
            model_name='codereview',
            name='file_name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
